#!/usr/bin/env python3
"""Generate `quests-data.js` from the quest extraction in runescape-research.

Source: `jsonl/quest_details.jsonl`, written by that project's
`runescape_quests_fetcher.py` (OSRS wiki `bucket("quest")` + `{{Quest rewards}}`
+ LostCityRS/Content).

Like `build-changes-data.py`, this writes ONLY its own generated file. It reads
`updates-data.js` to find which quests the roadmap actually names, and never
writes it -- that file carries hand edits (PINNED, star, note, hide, and now
`unconfirmed`) and has no generator by design.

Two things this deliberately does not do:

* **It does not merge the wiki and Content numbers.** The wiki describes the
  quest as OSRS has it today; a Content branch describes what a preservation
  build ships for 2005. Where they disagree, that disagreement is the only
  evidence of drift there is, so both go in the output and the page shows the
  wiki value with the build value marked beside it.
* **It does not drop the "documented today" caveat.** Requirements drift and
  `difficulty`/`length` are modern wiki gradings that did not exist in 2005.

Two things it does do, both narrowing:

* **Anachronism filter.** A reward list is written for the game as it is now, so
  it cites things that did not exist when the quest shipped: Monkey Madness
  offers a dragon scimitar (released 2005-03-29, four months later), Troll
  Romance unlocks a boss "in the Nightmare Zone" (2013), In Search of the
  Myreque hands out a fairy ring (2006-07). Every bullet's wiki links are dated
  by the extractor, and a bullet naming anything released after the build it
  sits under is dropped. Five of the seven anachronisms found by hand are caught
  this way; the two that are not -- ring of wealth *teleports* (2008, on an item
  that existed in 2004) and *elite* clue scrolls (2010, on a page that predates
  them) -- are phrase rules in ANACHRONISMS below, because dating the linked
  page cannot see them.
* **Reward buff correction.** OSRS has raised some quest XP rewards since 2005
  -- Swan Song's Fishing award went from 10,000 to 50,000 on 2022-11-30. The
  anachronism filter cannot see this, because a rebalanced number links no new
  page. `REWARD_BUFFS` carries the corrections read off `{{Subject changes}}` on
  the quest page, the only place they are recorded.

* **Requirements are narrowed to quests and skills.** Start point, items needed
  and enemies to defeat are dropped entirely: they are the fields most likely to
  describe a modern route through the quest rather than the 2005 one.

Usage:  python tools/build-quests-data.py [--research DIR] [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
RESEARCH = Path(r"F:\projects\runescape-research")

OUT = HERE / "quests-data.js"

HEADER = """// GENERATED by tools/build-quests-data.py - do not hand-edit.
// Source: OSRS Wiki bucket("quest") + {{Quest rewards}} (CC BY-NC-SA 3.0 - see
// the page footer for attribution), and LostCityRS/Content.
//
// REQUIREMENTS AND REWARDS HERE DESCRIBE THE QUEST AS OSRS DOCUMENTS IT TODAY,
// not as it shipped in 2005. `difficulty` and `length` are present-day wiki
// gradings that did not exist then. `lc` carries what a Lost City preservation
// branch implements, kept separate on purpose: where the two disagree, that
// disagreement is the drift.
//
// SOURCE PRECEDENCE for any single value: the Lost City Content branch first
// (`lc` -- period data by construction), then a wiki figure corrected for a
// documented buff (`buffs`), then the wiki figure as it stands. Losing values
// are shown, never discarded: the disagreement is the only drift signal there is.
//
// `buffs` lists XP rewards OSRS raised after 2005. The bullet above shows the
// value the quest paid at this build; `now` is what the wiki reports today.
//
// A bullet is { d: depth, p: [parts] } where a part is a string (plain text) or
// [label, page] (a wiki link).
"""


SKILLS = (
    "Attack|Strength|Defence|Ranged|Prayer|Magic|Runecraft|Runecrafting|Hitpoints|"
    "Constitution|Crafting|Mining|Smithing|Fishing|Cooking|Firemaking|Woodcutting|"
    "Agility|Herblore|Thieving|Fletching|Slayer|Farming|Construction|Hunter|Summoning"
)
# "70 Cooking", "level 60 Attack", "48 Agility [not boostable]"
SKILL_REQ = re.compile(r"\b\d+\s+(?:%s)\b" % SKILLS)
QUEST_POINTS = re.compile(r"\bquest points?\b", re.I)

# Anachronisms that dating the linked page cannot catch, because the page itself
# is old and only the *capability* is new. Keep this list short and dated -- each
# entry is a claim about when something arrived, and a wrong one silently hides a
# real reward.
ANACHRONISMS = [
    # Ring of wealth is a 2004 item; its teleports arrived in 2008.
    (re.compile(r"teleport.{0,40}ring of wealth|ring of wealth.{0,40}teleport", re.I),
     "ring of wealth teleports (2008)"),
    # Clue scrolls are 2004; the elite tier is 2010.
    (re.compile(r"\belite\b.{0,20}clue|clue.{0,20}\belite\b", re.I),
     "elite clue scrolls (2010)"),
    # The Wizards' Guild rune store had no quest gate in 2006 -- OSRS made
    # completing The Hand in the Sand a requirement to buy there on 2018-06-28,
    # and only then did access become a "reward". Both linked pages long predate
    # that, and RS3 does not list the reward at all.
    (re.compile(r"wizard.{0,3}s.{0,3}guild.{0,25}rune store"
                r"|magic guild store.{0,30}runes and staves", re.I),
     "Wizards' Guild rune store access (gated 2018, OSRS only)"),
]


# Quest XP rewards that OSRS has since raised. Dating the linked page cannot see
# these -- a rebalanced *quantity* links nothing new -- so they are the one class
# of drift that passes the anachronism filter silently.
#
# Sourced from {{Subject changes}} on the quest page itself, which is the only
# place this is recorded: a probe of the 292 pages linked from quest rewards
# found 595 change entries and exactly one dated before 2008, none of them a
# reward buff. `tools/probe-quest-buffs.py` re-runs the scan.
#
# Each row is (quest, skill, period value, the value the wiki shows now, date).
# If the wiki figure stops matching `now`, the row is NOT applied and the build
# warns -- a second buff must be read and added, never guessed at.
REWARD_BUFFS: list[tuple[str, str, int, int, str]] = [
    # 2022-11-30, "the experience rewarded ... was increased from X to Y".
    ("Mourning's End Part I",  "Thieving", 25_000, 40_000, "2022-11-30"),
    ("Mourning's End Part II", "Agility",  20_000, 60_000, "2022-11-30"),
    ("Swan Song",              "Fishing",  10_000, 50_000, "2022-11-30"),
]


def apply_reward_buffs(quest: str, bullets: list[dict]) -> tuple[list[dict], list[dict]]:
    """Rewrite post-buff XP figures back to what the quest paid at its build.

    Matches on the shape the wiki writes these in -- a leading text part holding
    the number, then a link to the skill -- and only when the number still reads
    as the value the table was written against. Returns the bullets and one
    record per correction so the page can show what was changed and when, rather
    than quietly substituting a different number than the wiki has.
    """
    rows = [r for r in REWARD_BUFFS if r[0] == quest]
    if not rows:
        return bullets, []
    applied: list[dict] = []
    for _, skill, was, now, date in rows:
        want = f"{now:,}"
        hit = False
        for b in bullets:
            parts = b["parts"]
            if not parts or parts[0]["t"] != "text" or want not in parts[0]["v"]:
                continue
            links = [p["page"] for p in parts if p["t"] == "link"]
            if skill not in links:
                continue
            parts[0]["v"] = parts[0]["v"].replace(want, f"{was:,}", 1)
            applied.append({"skill": skill, "was": was, "now": now, "date": date})
            hit = True
            break
        if not hit:
            print(f"  ! buff not applied: {quest} / {skill} -- wiki no longer reads "
                  f"{want}; re-read {{{{Subject changes}}}} on the quest page",
                  file=sys.stderr)
    return bullets, applied


def quest_dates(root: Path) -> dict[str, str]:
    """Quest name -> the date of the update that adds it, via node."""
    out = subprocess.run(
        ["node", str(root / "tools" / "quest-dates.mjs")],
        capture_output=True, text=True, cwd=root, check=True, shell=(sys.platform == "win32"),
    )
    return json.loads(out.stdout)


def filter_bullets(bullets: list[dict], link_dates: dict[str, str], cutoff: str,
                   *, quests_only: bool = False, known_quests: set[str] | None = None,
                   ) -> tuple[list[dict], int]:
    """Drop anachronistic bullets; optionally keep only quest/skill requirements.

    Returns the surviving bullets and how many were dropped, so the page can say
    that something was hidden rather than silently showing a short list.
    """
    kept: list[dict] = []
    dropped = 0
    for b in bullets:
        text = "".join(p["v"] if p["t"] == "text" else p["v"] for p in b["parts"])
        links = [p["page"] for p in b["parts"] if p["t"] == "link"]
        late = [n for n in links if link_dates.get(n, "") > cutoff]
        phrase = any(rx.search(text) for rx, _ in ANACHRONISMS)
        if late or phrase:
            dropped += 1
            continue
        if quests_only:
            is_quest = any(n in (known_quests or ()) for n in links)
            if not (is_quest or SKILL_REQ.search(text) or QUEST_POINTS.search(text)):
                # A parent heading ("Completion of the following quests:") has no
                # requirement of its own; keep it only if something under it did.
                if b["depth"] < 2 and text.rstrip().endswith(":"):
                    kept.append(b)
                    continue
                dropped += 1
                continue
        kept.append(b)
    # A heading left with nothing under it is noise.
    out: list[dict] = []
    for i, b in enumerate(kept):
        text = "".join(p["v"] for p in b["parts"]).rstrip()
        if text.endswith(":") and (i + 1 >= len(kept) or kept[i + 1]["depth"] <= b["depth"]):
            continue
        out.append(b)
    return out, dropped


def read_roadmap_quests(path: Path) -> set[str]:
    """Every name in a `type: "Quest"` group in updates-data.js."""
    src = path.read_text(encoding="utf-8")
    names: set[str] = set()
    for group in re.findall(r'\{\s*type:\s*"Quest",\s*names:\s*\[(.*?)\]\s*\}', src, re.S):
        names |= set(re.findall(r'"([^"]+)"', group))
    return names


def compact(bullets: list[dict]) -> list[dict]:
    """Shrink the jsonl bullet shape for the browser.

    `{"t":"text","v":"x"}` becomes `"x"` and `{"t":"link","v":"l","page":"p"}`
    becomes `["l","p"]` -- or just `"l"` when label and page match, which is the
    common case. Roughly halves the file.
    """
    out = []
    for b in bullets:
        parts = []
        for p in b["parts"]:
            if p["t"] == "text":
                if p["v"]:
                    parts.append(p["v"])
            elif p["v"] == p["page"]:
                parts.append([p["v"]])
            else:
                parts.append([p["v"], p["page"]])
        if parts:
            out.append({"d": b["depth"], "p": parts})
    return out


def js(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--research", type=Path, default=RESEARCH)
    ap.add_argument("--check", action="store_true", help="report the join, write nothing")
    args = ap.parse_args()

    src = args.research / "jsonl" / "quest_details.jsonl"
    if not src.exists():
        print(f"missing {src}\nrun: python runescape_quests_fetcher.py --full", file=sys.stderr)
        return 2

    rows = {}
    with src.open(encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            rows[r["quest"]] = r

    wanted = read_roadmap_quests(HERE / "updates-data.js")
    missing = sorted(wanted - set(rows))
    used = sorted(wanted & set(rows))

    no_req = [q for q in used if not rows[q]["requirements"]]
    no_rew = [q for q in used if not rows[q]["rewards"]]
    with_lc = [q for q in used if rows[q]["lostcity"]]

    print(f"roadmap quests:        {len(wanted)}")
    print(f"  matched in dataset:  {len(used)}")
    print(f"  no requirements:     {len(no_req)}{' ' + ', '.join(no_req) if no_req else ''}")
    print(f"  no rewards:          {len(no_rew)}{' ' + ', '.join(no_rew) if no_rew else ''}")
    print(f"  Lost City build data:{len(with_lc)} ({', '.join(with_lc)})")
    if missing:
        print(f"  NOT IN DATASET:      {len(missing)}: {', '.join(missing)}")
    if args.check:
        return 0

    dates = quest_dates(HERE)
    all_quests = set(rows)
    lines = [HEADER, "export const QUESTS = {"]
    total_dropped = 0
    total_buffed = 0
    for q in used:
        r = rows[q]
        cutoff = dates.get(q, "2006-05-02")
        req, dreq = filter_bullets(r["requirements"], r["link_dates"], cutoff,
                                   quests_only=True, known_quests=all_quests)
        rew, drew = filter_bullets(r["rewards"], r["link_dates"], cutoff)
        # After filtering, not before: a bullet the date filter drops needs no
        # correcting, and correcting it first would change the text it matches on.
        rew, buffs = apply_reward_buffs(q, rew)
        total_dropped += dreq + drew
        total_buffed += len(buffs)
        obj = {
            "url": r["url"],
            "difficulty": r["difficulty"],
            "length": r["length"],
            "qp": r["quest_points"],
            "requirements": compact(req),
            "rewards": compact(rew),
            # How many lines the anachronism filter removed, so the page can say
            # so instead of quietly showing a shorter list.
            "cut": dreq + drew,
        }
        # Only present when something was corrected, so the common case costs
        # nothing in the shipped file.
        if buffs:
            obj["buffs"] = buffs
        lc = r["lostcity"]
        if lc:
            # One skill can carry two values: Monkey Madness pays 35,000 or
            # 20,000 to each combat skill depending on what the player tells
            # Daero, and both branches of that `if` are in the script. Listing
            # them flat reads as eight separate awards, so they collapse to a
            # range and the page renders "20,000-35,000 attack".
            by_skill: dict[str, set[int]] = {}
            for x in lc["xp_awards"]:
                by_skill.setdefault(x["skill"], set()).add(x["xp"])
            obj["lc"] = {
                "branch": lc["branch"],
                "qp": lc["quest_points"],
                "items": [{"obj": i["obj"], "n": i["count"]} for i in lc["items"]],
                "xp": [{"skill": k, "xp": sorted(v)} for k, v in sorted(by_skill.items())],
            }
        lines.append("  %s: %s," % (js(q), js(obj)))
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  bullets dropped:     {total_dropped} (anachronistic, or not a quest/skill requirement)")
    print(f"  XP figures corrected:{total_buffed} (post-2005 reward buffs, see REWARD_BUFFS)")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
